spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankDb
    username: postgres
    password: 6eight14
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: bank-sys
  mail:
    host: smtp.gmail.com
    port: 587
    username: piusobonyo5@gmail.com
    password: ywersrewrwr
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  secret: e83f3851fa7407cb60737b93251ce8ca0c85ccfef4bb304792f7fe2a4cb7cb39e83f3851fa7407cb60737b93251ce8ca0c85ccfef4bb304792f7fe2a4cb7cb39

server:
  port: 8082




